### ISSUE TITLE
Alternative to Playstore

### ISSUE THREAD

**Issue by IzzySoft** [jamiesanson/Mammut#4]
Would you consider using an alternative download source for those running their devices free of Google? Easiest way would be attaching the APK to the `releases/` here on Github – but bringing it to F-Droid would be excellent.

**Comment by jamiesanson** [comment]
Great idea! I'm a little way off properly distributing this app, I've got a lot of work to do to get it up to a level where I want to ship it properly, so for now I'll stick with Google Play Beta. I will be considering alternate app stores when moving this app out of beta, but for now it's easiest to keep it where it is. 

Cheers

**Comment by IzzySoft** [comment]
Thanks for considering! But currently, that means excluding users whose devices run without Google. May I suggest to at least provide the APK via the `releases/` – and keeping this issue open as reminder for the rest?

**Comment by jamiesanson** [comment]
To follow up on this, I've begun adding the App bundles to the releases section here on Github. Installing these is a bit more of a pain compared to regular APKs, but if you so wish go ahead and try out [bundletool](https://developer.android.com/studio/command-line/bundletool)

**Comment by IzzySoft** [comment]
Couldn't you just attach the APK files, signed with your key? That would make it much easier, and I could offer to serve them via [my F-Droid compatible repo](https://apt.izzysoft.de/fdroid/repo). And before you ask: No, I don't have the Android SDK installed anywhere, I'm not an Android dev 😉

**Comment by jamiesanson** [comment]
Hey,

Hate to be the bearer of bad news, but I've been considering making the app paid on the Play Store to give me motivation to spend more time working on it. I'll be moving this repository to my Github org, K-OSS. I plan on keeping the code open source, changing the license to GPL 3.0, but due to the fact that I plan on eventually integrating the app with paid services (i.e for support of push notifications) I will not be bundling APK/AAB files with the repository. Should one wish to install Mammut for free that will still be doable by building from source and supplying their own keys for these paid services.

Sorry for the inconvenience,
Jamie

**Comment by IzzySoft** [comment]
That's indeed not "good news" for some. Still, let me point out that several other projects have done so – and still offer their apps for free in F-Droid. Examples are OsmAnd and DAVDroid. Just saying (hope dies last). So would you oppose F-Droid building the APK from your sources, and publish it in its repo?
